---
title: "Fig 7: Motivations for contributing to OS"
---

# Overview
This notebook is for final tweaks to fig 7, which is from Q6 on motivations.

# Import packages and utilities
```{r}
project_root <- here::here() # requires that you be somewhere in the
# project directory (not above it)
# packages
suppressMessages(source(file.path(project_root, "scripts/packages.R")))
# functions and objects used across scripts
suppressMessages(source(file.path(project_root, "scripts/utils.R")))
```

# Define functions
```{r}
line_plot <- function(df, x_var, y_var, title) {
  p <- ggplot(df, aes(x = .data[[x_var]], y = .data[[y_var]])) +
    geom_point(size = 1) + # Adjust dot size
    scale_y_continuous(labels=scales::percent) +
    labs(
      title = title
    ) +
    theme(
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      axis.text.x = element_text(angle = 60, vjust = 0.6, size = 6),
      axis.text.y = element_text(size = 6),
      axis.ticks.x = element_blank(),
      axis.ticks.y = element_blank(),
      legend.title = element_blank(),
      plot.title = element_text(
        hjust = 0,
        face = "bold",
        size = 7,
        margin = margin(b = 5)
      ),
      plot.margin = unit(c(0.3, 0.3, 0.3, 0.9), "cm"),
      panel.grid = element_line(linetype = "solid", color = "gray90"),
      panel.background = element_blank()
    )
  return(p)
}
```

# Load data

```{r}
basic_data <- read.csv(
    file.path(
      DATA_PATH,
      "data_for_plots",
      "motivations_basic_bar.tsv"
    ),
    stringsAsFactors = TRUE,
    sep = "\t"
  )
basic_data$Motivation <- gsub("Improve Tools", "Improve tools", basic_data$Motivation)


it_acad_data <- read.csv(
    file.path(
      DATA_PATH,
      "data_for_plots",
      "motivations_it_acad.tsv"
    ),
    stringsAsFactors = TRUE,
    sep = "\t"
  )

skills_data <- read.csv(
    file.path(
      DATA_PATH,
      "data_for_plots",
      "motivations_skills.tsv"
    ),
    stringsAsFactors = TRUE,
    sep = "\t"
  )
```

Order factor levels

```{r}
basic_data <- basic_data %>%
  mutate(Motivation = fct_reorder(Motivation, Count, .desc = FALSE))

skills_data$job_category <- factor(skills_data$job_category, 
levels = c(
      "Undergraduate",
      "Grad Student",
      "Post-Doc",
      "Faculty"
    )
)
```


```{r}
basic_plot <- basic_bar_chart(basic_data,
  x_var = "Motivation",
  y_var = "Count",
  title = "Reasons for contributing to open source",
  horizontal = TRUE,
  show_bar_labels = TRUE,
  show_ticks_y = FALSE,
  color_index = 3,
  axis_title_size_x = 6,
  axis_title_size_y = 6,
  axis_text_size_x = 6,
  axis_text_size_y = 6,
  title_size = 7,
  label_size = 2,
  show_axis_title_x = TRUE,
  x_axis_title_margin_t = 5,
  show_axis_title_y = FALSE,
  show_grid = TRUE
)

it_acad_job_plot <- ggplot(it_acad_data, aes(x = role, y = proportion_yes, fill = role)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c("#1a7937", "#eecc66"))+
  scale_y_continuous(labels = scales::percent)+
  ggtitle("Percent of respondents who said\n'Developing open source products\nis part of my job'")+
  theme(
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  axis.text.x = element_text(
        angle = 60,
        vjust = 0.6,
        size = 6
      ),
  axis.text.y = element_text(size = 6),
  axis.ticks.x = element_blank(),
  axis.ticks.y = element_blank(),
  panel.grid = element_line(linetype = "solid", color = "gray90"),
  panel.background = element_blank(),
  legend.key.size = unit(rel(0.5), "lines"),
  legend.text = element_text(
    size = 6,
    margin = margin(l = 1)
  ),
  legend.title = element_blank(),
  plot.title = element_text(
    hjust = 0,
    face = "bold",
    size = 7
    ),
  plot.margin = unit(c(0.6, 0.3, 0.3, 0.3), "cm")
  )


skills_plot <- line_plot(skills_data,
x_var = "job_category",
y_var = "Proportion",
title = "Percent of participants motivated\nby desire to improve their skills"
)
```



```{r}
# From the patchwork package
top_row <- basic_plot + plot_spacer() + plot_layout(widths = c(1.5, 0.5))
bottom_row <- skills_plot + it_acad_job_plot + plot_layout(widths = c(1.1, 0.9))

p_combined <- top_row / bottom_row

ggsave(
  filename = file.path(FIGURE_PATH, "fig7.tif"),
  plot = p_combined + plot_annotation(tag_levels = "A") & theme(plot.tag = element_text(size = 7)),
  device = "tiff",
  width = 5.2, height = 5, units = "in",
  dpi = 310,                
  compression = "none",    
  bg = "white"
)
```