# Edit this list to add or remove packages
# After editing, update the lockfile by running renv::snapshot()
library(corrplot)
library(dplyr)
library(forcats)
library(ggplot2)
library(gtools)
library(here)
library(mvabund)
library(patchwork)
library(pwr)
library(readr)
library(scales)
library(stringr)
library(tidyr)
library(tools)
