# Edit this list to add or remove packages
# After editing, update the lockfile by running renv::snapshot()
library(cluster)
library(corrplot)
library(dplyr)
library(emmeans)
library(factoextra)
library(forcats)
library(fpc)
library(ggforce)
library(ggplot2)
library(gtools)
library(here)
library(languageserver)
library(lme4)
library(ordinal)
library(patchwork)
library(pwr)
library(readr)
library(scales)
library(stringr)
library(svglite)
library(tidyr)
library(tools)
library(treemap)
